# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  OpenGLPaint_config = debug
  ImGui_config = debug
endif
ifeq ($(config),release)
  OpenGLPaint_config = release
  ImGui_config = release
endif

PROJECTS := OpenGLPaint ImGui

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

OpenGLPaint: ImGui
ifneq (,$(OpenGLPaint_config))
	@echo "==== Building OpenGLPaint ($(OpenGLPaint_config)) ===="
	@${MAKE} --no-print-directory -C . -f OpenGLPaint.make config=$(OpenGLPaint_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C vendor -f Makefile config=$(ImGui_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f OpenGLPaint.make clean
	@${MAKE} --no-print-directory -C vendor -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   OpenGLPaint"
	@echo "   ImGui"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"